fmod PARAM is
    sorts Param ConstVariable FreeVariable .
    subsorts ConstVariable FreeVariable < Param .
endfm

view Param from TRIV to PARAM is
    sort Elt to Param .
endv

fmod PARAM-LIST is
    pr LIST{Param} * (
        sort NeList{Param} to NeParamList, 
        sort List{Param} to ParamList,
        op __ to _`,_
    ) .
endfm

fmod PRED is
    sort Pred .
endfm

view Pred from TRIV to PRED is
    sort Elt to Pred .
endv

fmod PRED-LIST is
    pr LIST{Pred} * (
        sort NeList{Pred} to NePredList, 
        sort List{Pred} to PredList
    ) .
endfm

fmod LITERAL is
    pr PRED-LIST .
    pr PARAM-LIST .
    sort Literal .
    op _`(_`) : Pred ParamList -> Literal .
endfm

view Literal from TRIV to LITERAL is
    sort Elt to Literal .
endv

fmod LITERAL-LIST is
    pr LIST{Literal} * (
        sort NeList{Literal} to NeLiteralList, 
        sort List{Literal} to LiteralList
    ) .
endfm

fmod RULE is
    pr LITERAL-LIST .
    sorts FOVar SOVar .
    subsort Pred < SOVar .
    subsort Param < FOVar .
    sorts Head Body Rule .
    subsort Literal < Head .
    subsort LiteralList < Body .
    op _:-_ : Head Body -> Rule [prec 120].
    op _:- : Head -> Rule [prec 110].
endfm

view Rule from TRIV to RULE is
    sort Elt to Rule .
endv

fmod RULE-LIST is
    pr LIST{Rule} * (
        sort NeList{Rule} to NeRuleList, 
        sort List{Rule} to RuleList
    ) .
endfm

fmod ILP-DEFINITION-INPUT is
    pr RULE-LIST .
    ops BK POS NEG : -> PredList .
    op METARULES : -> RuleList .
endfm

fmod ILP-PROBLEM is 
    pr ILP-DEFINITION-INPUT .
    
    ----------------------------------------------------------
    --- Overwrite this module with the ILP problem
    ----------------------------------------------------------

    sort Person .
    subsort Person < Param .

    ops ann bob cal dawn : -> Person [ctor] .

    ops parent grandparent great-grandparent : Person Person -> Pred [ctor] .

    eq BK =
        parent(ann, bob)
        parent(bob, cal)
        parent(cal, dawn) .


    eq POS =
        great-grandparent(ann, dawn) .

    eq NEG = grandparent(ann, dawn) .

    vars P Q R : Pred .
    vars A B C : Person .

    eq METARULES =
        (P(A,B) :- (Q(A,C)) (R(C,B)))
        [nonexec] .
endfm

fmod MODULE-HANDLING is
    pr META-LEVEL .
    vars EqS : EquationSet .
    vars AtS : AttrSet .
    vars C : Constant .
    vars T T' : Term .
    vars M : Module .
    vars Q : Qid .

    op getEqsOfQid : Module Qid -> EquationSet .
    op getEqsOfQid : EquationSet Qid -> EquationSet .
    eq getEqsOfQid(M, Q) = getEqsOfQid(getEqs(M), Q) .
    ceq getEqsOfQid((eq C = T [AtS] .) EqS, Q) = (eq C = T [AtS] .) if Q == C .
    eq getEqsOfQid(EqS, Q) = none [owise] .

    ops lhsEq rhsEq : Equation -> Term .
    eq lhsEq((eq T = T' [AtS] .)) = T .
    eq rhsEq((eq T = T' [AtS] .)) = T' .
endfm

fmod TERM-SET is
    pr META-LEVEL .
    sort TermSet .
    subsort Term < TermSet .
    op emptyTS : -> TermSet [ctor] .
    op _|_ : TermSet TermSet -> TermSet [ctor assoc comm id: emptyTS format (d n d d)] .
    eq X:Term | X:Term = X:Term .

    op _in_ : Term TermSet -> Bool .
    eq T:Term in (T:Term | TS:TermSet) = true .
    eq T:Term in TS:TermSet = false [owise] .
    op TermSet : TermList -> TermSet .
    eq TermSet(empty) = emptyTS .
    eq TermSet((T:Term,TL:TermList)) = T:Term | TermSet(TL:TermList) .
endfm

fmod META-TERM-EXT is
    pr META-TERM .
    pr TERM-SET .

    sort BindVal .
    subsorts Qid Term < BindVal .

    sorts NeVarList VarList .
    subsorts Variable < NeVarList < NeTermList VarList < TermList .
    op _,_ : VarList VarList -> VarList [ctor ditto] .
    op _,_ : NeVarList VarList -> NeVarList [ctor ditto] .
    op _,_ : VarList NeVarList -> NeVarList [ctor ditto] .

    op sizeTL : TermList -> Nat .
    eq sizeTL(empty) = 0 .
    eq sizeTL((T:Term, TL:TermList)) = sizeTL(TL:TermList) + 1 .
endfm

fmod META-LITERAL is
    pr META-TERM-EXT .
    sorts MetaLiteral BoundLiteral GroundLiteral .
    subsorts MetaLiteral GroundLiteral < BoundLiteral .
    op _<>_ : Qid NeTermList -> BoundLiteral .
    op _<>_ : Variable NeVarList -> MetaLiteral .
    op _<>_ : Qid NeGroundTermList -> GroundLiteral .
    
    vars NeGTL : NeGroundTermList .
    vars NeTL : NeTermList .
    vars Q : Qid .
    
    op getSOVar : BoundLiteral -> Qid .
    op getSOVar : GroundLiteral -> Qid .
    op getSOVar : MetaLiteral -> Variable .
    eq getSOVar(Q <> NeTL) = Q .
    
    op getFOVars : BoundLiteral -> NeTermList .
    op getFOVars : GroundLiteral -> NeGroundTermList .
    op getFOVars : MetaLiteral -> NeVarList .
    eq getFOVars(Q <> NeTL) = NeTL .
    
    op getNumOfAriry : BoundLiteral -> Nat .
    eq getNumOfAriry(Q <> NeTL) = sizeTL(NeTL) .
    
    op toGroundTerm : GroundLiteral -> GroundTerm .
    eq toGroundTerm(Q <> NeGTL) = Q[NeGTL] .
    
    op toTerm : BoundLiteral -> Term .
    eq toTerm(Q <> NeTL) = Q[NeTL] .

    op hasSOVarOnly : BoundLiteral -> Bool .
    eq hasSOVarOnly(Q <> NeGTL) = Q :: Variable .
    eq hasSOVarOnly(Q <> NeTL) = false [owise] .
    
    op isGroundLiteral : BoundLiteral -> Bool .
    eq isGroundLiteral(Q <> NeGTL) = not (Q :: Variable) .
    eq isGroundLiteral(Q <> NeTL) = false .
endfm

view BoundLiteral from TRIV to META-LITERAL is
    sort Elt to BoundLiteral .
endv

fmod META-LITERAL-LIST is
    pr LIST{BoundLiteral} * (
        sort NeList{BoundLiteral} to NeBoundLiteralList, 
        sort List{BoundLiteral} to BoundLiteralList
    ) .
    sorts NeMetaLiteralList MetaLiteralList NeGroundLiteralList GroundLiteralList .
    subsorts MetaLiteral < NeMetaLiteralList < NeBoundLiteralList MetaLiteralList < BoundLiteralList .
    subsorts GroundLiteral < NeGroundLiteralList < NeBoundLiteralList GroundLiteralList < BoundLiteralList .
    op __ : MetaLiteralList MetaLiteralList -> MetaLiteralList [ctor ditto] .
    op __ : NeMetaLiteralList MetaLiteralList -> NeMetaLiteralList [ctor ditto] .
    op __ : MetaLiteralList NeMetaLiteralList -> NeMetaLiteralList [ctor ditto] .
    op __ : GroundLiteralList GroundLiteralList -> GroundLiteralList [ctor ditto] .
    op __ : NeGroundLiteralList GroundLiteralList -> NeGroundLiteralList [ctor ditto] .
    op __ : GroundLiteralList NeGroundLiteralList -> NeGroundLiteralList [ctor ditto] .
    op nil : -> MetaLiteralList .
endfm

fmod META-RULE is
    pr META-LITERAL-LIST .
    sorts MetaRule BoundRule .
    subsort MetaRule < BoundRule .
    op _:-_ : MetaLiteral MetaLiteralList -> MetaRule .
    op _:-_ : BoundLiteral BoundLiteralList -> BoundRule .
    op getHead : MetaRule -> MetaLiteral .
    op getHead : BoundRule -> BoundLiteral .
    op getBody : MetaRule -> MetaLiteralList .
    op getBody : BoundRule -> BoundLiteralList .
    eq getHead(BL:BoundLiteral :- BLL:BoundLiteralList) = BL:BoundLiteral .
    eq getBody(BL:BoundLiteral :- BLL:BoundLiteralList) = BLL:BoundLiteralList .
endfm

view BoundRule from TRIV to META-RULE is
    sort Elt to BoundRule .
endv

fmod RENAME-VARS is
    pr META-TERM-EXT .
    pr META-RULE .
    pr CONVERSION .

    vars V : Variable .
    vars N : Nat .
    vars ML : MetaLiteral .
    vars MLL : MetaLiteralList .
    vars S S1 S2 : String .
    vars Pos : Nat .

    op renameVar : Variable Nat -> Variable .
    ceq renameVar(V, N) = qid(S1 + string(N, 10) + ":" + S2)
      if S := string(V)
      /\ Pos := find(S, ":", 0)
      /\ S1 := substr(S, 0, Pos)
      /\ S2 := substr(S, Pos + 1, length(S)) .

    op renameNeVarList : NeVarList Nat -> NeVarList .
    eq renameNeVarList(V:Variable, N) = renameVar(V:Variable, N) .
    eq renameNeVarList((V:Variable, VL:NeVarList), N) = renameVar(V:Variable, N), renameNeVarList(VL:NeVarList, N) .

    op renameVarsML : MetaLiteral Nat -> MetaLiteral .
    eq renameVarsML(V:Variable <> VL:NeVarList, N) = renameVar(V:Variable, N) <> renameNeVarList(VL:NeVarList, N) .

    op renameVarsMLL : MetaLiteralList Nat -> MetaLiteralList .
    eq renameVarsMLL(nil, N) = nil .
    eq renameVarsMLL(ML MLL, N) = renameVarsML(ML, N) renameVarsMLL(MLL, N) .

    op renameVarsMR : MetaRule Nat -> MetaRule .
    eq renameVarsMR(ML :- MLL, N) = renameVarsML(ML, N) :- renameVarsMLL(MLL, N) .
endfm

fmod META-RULE-SET is
    pr SET{BoundRule} * (
        sort NeSet{BoundRule} to NeBoundRuleSet, 
        sort Set{BoundRule} to BoundRuleSet
    ) .
    sorts NeMetaRuleSet MetaRuleSet .
    subsorts MetaRule < NeMetaRuleSet < NeBoundRuleSet .
    subsorts NeMetaRuleSet < MetaRuleSet < BoundRuleSet .
    op _,_ : MetaRuleSet MetaRuleSet -> MetaRuleSet [ctor ditto] .
    op _,_ : MetaRuleSet NeMetaRuleSet -> NeMetaRuleSet [ctor ditto] .
    op _,_ : NeMetaRuleSet MetaRuleSet -> NeMetaRuleSet [ctor ditto] .

    vars BLL : BoundLiteralList .
    vars BRS : BoundRuleSet .
    vars NeTL : NeTermList .
    vars Q : Qid .

    op hasRuleByQid : Qid BoundRuleSet -> Bool .
    eq hasRuleByQid(Q, ((Q <> NeTL :- BLL), BRS)) = true . 
    eq hasRuleByQid(Q, BRS) = false [owise] .
endfm

fmod PARSING is
    pr MODULE-HANDLING .
    pr META-RULE-SET .
    pr CONVERSION .
    
    vars GLit : GroundLiteral .
    vars NeTL : NeTermList .
    vars EQ : Equation .
    vars TL : TermList .
    vars TS : TermSet .
    vars T T' : Term .
    vars M : Module .
    vars Q : Qid .
    vars N : Nat .
    vars C : Constant .

    op parseItems : Module Qid -> TermSet .
    ceq parseItems(M, Q) = parseItems*(rhsEq(EQ)) if EQ := getEqsOfQid(M, Q) .
    eq parseItems(M, Q) = emptyTS .
    op parseItems* : Term -> TermSet .
    eq parseItems*('__[T, T']) = T | parseItems*(T') .
    eq parseItems*(T) = T [owise] .
    
    op parseRules : Module Qid -> MetaRuleSet .
    ceq parseRules(M, Q) = parseRules*(rhsEq(EQ)) if EQ := getEqsOfQid(M, Q) .
    eq parseRules(M, Q) = empty [owise] .
    op parseRules* : Term -> MetaRuleSet .
    eq parseRules*('__[T, T']) = parseRule(T), parseRules*(T') .
    eq parseRules*(T) = parseRule(T) .
    op parseRule : Term -> MetaRuleSet .
    eq parseRule('_:-_[T, T']) = parseLiteral(T) :- parseBody(T') .
    eq parseRule('_:-[T]) = parseLiteral(T) :- nil .
    eq parseRule(T) = empty [owise] .

    op parseLiteral : Term -> MetaLiteral .
    eq parseLiteral('_`(_`)[T, T']) = T <> parseParams(T') .

    op parseParams : Term -> TermList .
    eq parseParams('_`,_[TL]) = TL .
    eq parseParams(T) = T [owise] .
    
    op parseBody : Term -> MetaLiteralList .
    eq parseBody('__[T, T']) = parseLiteral(T) parseBody(T') .
    eq parseBody(T) = parseLiteral(T) [owise] .

    op getPred : Term -> Qid .
    op getArgs : Term -> TermList .
    op getNumOfArgs : Term -> Nat .
    eq getPred(Q[NeTL]) = Q .
    eq getArgs(Q[NeTL]) = NeTL .
    eq getNumOfArgs(Q[NeTL]) = sizeTL(NeTL) .
    
    eq getPred(C) = getName(C) .
    eq getArgs(C) = empty .
    eq getNumOfArgs(C) = 0 .

    op hasElt : GroundLiteral TermSet -> Bool .
    eq hasElt(GLit, TS) = toGroundTerm(GLit) in TS .

    op getPredInvName : Nat -> Qid .
    eq getPredInvName(N) = qid("inv" + string(N + 1, 10)) .
endfm

fmod ILP-PARSING-INPUT is
    pr PARSING .
    op getBK`(`) : -> TermSet .
    op getPOS`(`) : -> TermSet .
    op getNEG`(`) : -> TermSet .
    op getMetaRules`(`) : -> MetaRuleSet .
    eq getBK() = parseItems(upModule('ILP-PROBLEM, false), 'BK.PredList) .
    eq getPOS() = parseItems(upModule('ILP-PROBLEM, false), 'POS.PredList) .
    eq getNEG() = parseItems(upModule('ILP-PROBLEM, false), 'NEG.PredList) .
    eq getMetaRules() = parseRules(upModule('ILP-PROBLEM, false), 'METARULES.RuleList) .
endfm

view Var from TRIV to META-TERM-EXT is
    sort Elt to Variable .
endv

view BindVal from TRIV to META-TERM-EXT is
    sort Elt to BindVal .
endv

fmod ENV is
    pr MAP{Var,BindVal} * (
        sort Entry{Var,BindVal} to Bind,
        sort Map{Var,BindVal} to Env
    ) .
    sorts ErrEnv Env&Err .
    subsort Env ErrEnv < Env&Err .
    op errEnv : -> ErrEnv [ctor] .
    eq errEnv, (V |-> BV) = errEnv .
    eq errEnv, errEnv = errEnv .
    
    vars BV? : [BindVal] .
    vars BV : BindVal .
    vars V : Variable .
    vars ENV : Env .
    op _**<<_ : Qid Env -> BindVal .
    ceq V **<< ENV = (if BV? == undefined then V else BV? fi) if BV? := ENV[V] .
    eq BV **<< ENV = BV [owise] .
endfm

fmod RULE-AND-ENV is
    pr META-RULE-SET .
    pr ENV .
    sort Rule&Env .
    op [_,_] : BoundRule Env -> Rule&Env .
endfm

view RuleAndEnv from TRIV to RULE-AND-ENV is
    sort Elt to Rule&Env .
endv

fmod PATH is
    pr LIST{RuleAndEnv} * (
        sort NeList{RuleAndEnv} to NePath, 
        sort List{RuleAndEnv} to Path
    ) .
endfm

fmod GOAL is
    pr META-TERM-EXT .
    pr BOUND .
    pr PATH .    
    pr META-RULE .
    pr ENV .

    sorts MetaContext BoundContext .
    op mctx : BoundLiteral BoundLiteralList MetaRule Env Nat -> MetaContext [ctor] .
    op bctx : BoundLiteral BoundLiteralList BoundRule Env Nat -> BoundContext [ctor] .
    
    sort ContextStack .
    subsorts MetaContext BoundContext < ContextStack .
    op emptyStack : -> ContextStack [ctor] .
    op _|_ : ContextStack ContextStack -> ContextStack [ctor assoc id: emptyStack] .

    sort Goal .
    op {goal:_,rules:_,path:_,depth:_,stack:_} : Term BoundRuleSet Path Bound ContextStack -> Goal .
    op {lits:_,facts:_,path:_,depth:_,stack:_} : BoundLiteralList TermSet Path Bound ContextStack -> Goal .
endfm

view Goal from TRIV to GOAL is
    sort Elt to Goal .
endv

fmod GOAL-LIST is
    pr LIST{Goal} * (
        sort NeList{Goal} to NeGoalList, 
        sort List{Goal} to GoalList
    ) .
endfm

fmod ILP-OUTPUT is
    pr PATH .
    pr ENV .
    
    vars MLL : BoundLiteralList .
    vars SOVar : Variable .
    vars ML : MetaLiteral .
    vars BR : BoundRule .
    vars MR : MetaRule .
    vars VL : VarList .
    vars PATH : Path .
    vars ENV : Env .
    vars T' : Term .
    vars S : Sort .
    
    op isConstantVar : Term -> Bool .
    ceq isConstantVar(V:Variable) = sortLeq(upModule('ILP-PROBLEM, false), S, 'ConstVariable) 
        if S := getType(V:Variable) .
    eq isConstantVar(T:Term) = false [owise] .

    op applyConstants : TermList Env -> TermList .
    eq applyConstants(empty, ENV) = empty .
    
    ceq applyConstants((V:Variable, TL:TermList), ENV) =
        (if isConstantVar(V:Variable)
         then T'
         else V:Variable fi) , applyConstants(TL:TermList, ENV)
    if T' := (V:Variable **<< ENV) .
    eq applyConstants((T:Term, TL:TermList), ENV) = T:Term , applyConstants(TL:TermList, ENV) [owise] .

    op buildClauseSet : Path -> BoundRuleSet .
    eq buildClauseSet(nil) = empty .
    eq buildClauseSet([MR, ENV] PATH) = buildClause(MR, ENV), buildClauseSet(PATH) .
    op buildClause : MetaRule Env -> BoundRule .
    eq buildClause(ML :- MLL, ENV) = buildBoundLiteral(ML, ENV) :- buildBoundLiteralList(MLL, ENV) .
    op buildBoundLiteralList : BoundLiteralList Env -> BoundLiteralList .
    eq buildBoundLiteralList(nil, ENV) = nil .
    eq buildBoundLiteralList(ML MLL, ENV) = buildBoundLiteral(ML, ENV) buildBoundLiteralList(MLL, ENV) .
    op buildBoundLiteral : BoundLiteral Env -> BoundLiteral .
    eq buildBoundLiteral(SOVar <> VL, ENV) = (SOVar **<< ENV) <> applyConstants(VL, ENV) .
    
    op buildClauseSet2 : Path -> BoundRuleSet .
    eq buildClauseSet2(nil) = empty .
    eq buildClauseSet2([BR, ENV] PATH) = BR, buildClauseSet2(PATH) .
endfm

fmod ENV-APPLYING is
    pr META-LITERAL . 
    pr ENV .

    vars BV? : [BindVal] .
    vars TL : TermList .
    vars V : Variable .
    vars BV : BindVal .
    vars ENV : Env .
    vars T : Term .
    vars Q : Qid .
    op _<<_ : BoundLiteral Env -> BoundLiteral .
    eq (Q <> TL) << ENV = (Q **<< ENV) <> (TL *<< ENV) .
    op _*<<_ : TermList Env -> TermList .
    eq (T, TL) *<< ENV = (T **<< ENV), (TL *<< ENV) .
    eq (empty *<< ENV) = empty .
    op _**<<_ : Qid Env -> BindVal .
    ceq V **<< ENV = (if BV? == undefined then V else BV? fi) if BV? := ENV[V] .
    eq BV **<< ENV = BV [owise] .
endfm

--- ====================================================================
--- NEW MODULE: TRANSFORMATION FROM SUBSTITUTION TO ENV
--- ====================================================================
fmod SUBST-TO-ENV is
    pr META-LEVEL .
    pr ENV .
    
    op toEnv : Substitution -> Env .
    eq toEnv(none) = empty .
    eq toEnv(V:Variable <- T:Term ; S:Substitution) = (V:Variable |-> T:Term), toEnv(S:Substitution) .
endfm

--- ====================================================================
--- UPDATED MODULE: LITERAL-MATCHING WITH AC-MATCHING DYNAMIC 100%
--- ====================================================================
fmod LITERAL-MATCHING is
    pr META-LITERAL .
    pr PARSING .
    pr ENV .
    pr SUBST-TO-ENV . --- add transformation from substitution to env

    vars BL : BoundLiteral .
    vars TL TL' : TermList .
    vars T T' : Term .
    vars G : Term .
    vars S : Sort .
    vars BV? : [BindVal] .
    vars ENV : Env .
    vars S? : [Substitution] .
    vars T_pat : Term .
    vars ENV_SO ExtractedEnv : Env&Err .
    vars Q : Qid .

    --- declare Reflection for Maude
    vars TyL : TypeList .
    vars Ty : Type .
    vars AtS : AttrSet .
    vars ODS : OpDeclSet .

    --- 1.  (META-REFLECTION)
    op isCommOp : Qid -> Bool .
    eq isCommOp(Q) = hasCommAttr(Q, getOps(upModule('ILP-PROBLEM, false))) .

    op hasCommAttr : Qid OpDeclSet -> Bool .
    eq hasCommAttr(Q, (op Q : TyL -> Ty [comm AtS] .) ODS) = true .
    eq hasCommAttr(Q, ODS) = false [owise] .

    --- 2. (SECOND-ORDER VARIABLE)
    op bindSOVar : Term BoundLiteral -> Env&Err .
    ceq bindSOVar(G, BL) = 
        if getSOVar(BL) :: Variable then 
            getSOVar(BL) |-> getPred(G) 
        else 
            if getSOVar(BL) == getPred(G) then empty else errEnv fi
        fi 
    if getNumOfArgs(G) == getNumOfAriry(BL) .
    eq bindSOVar(G, BL) = errEnv [owise] .

    op matchLiteral : Term BoundLiteral -> Env&Err .

    --- 3. PIPELINE 1: (SYNTACTIC MATCHING)
    --- For normal predicates (parent) and Predicate Invention (inv1)
    ceq matchLiteral(G, BL) = 
        if (ENV_SO == errEnv) or (ExtractedEnv == errEnv) then 
            errEnv 
        else 
            (ENV_SO , ExtractedEnv)
        fi
    if not isCommOp(getPred(G))
    /\ ENV_SO := bindSOVar(G, BL)
    /\ ExtractedEnv := matchArgs(getArgs(G), getFOVars(BL)) .

    --- 4. PIPELINE 2: (AC-MATCHING)
    --- For predicates WITH [comm] declaration in ILP-PROBLEM
    ceq matchLiteral(G, BL) = 
        if ENV_SO == errEnv then 
            errEnv 
        else 
            if S? :: Substitution then 
                ENV_SO , toEnv(S?)
            else 
                errEnv 
            fi
        fi
    if isCommOp(getPred(G))
    /\ ENV_SO := bindSOVar(G, BL)
    /\ T_pat := getPred(G)[getFOVars(BL)]
    /\ S? := metaMatch(upModule('ILP-PROBLEM, false), T_pat, G, nil, 0) .
    
    eq matchLiteral(G, BL) = errEnv [owise] .

    --- 5. PIPELINE 3: (CORE SYNTAX MATCHING)
    op matchArgs : TermList TermList -> Env&Err .
    op matchArgs* : TermList TermList Env -> Env&Err .
    
    eq matchArgs(TL, TL') = matchArgs*(TL, TL', empty) .

    eq matchArgs*(empty, empty, ENV) = ENV .
    ceq matchArgs*((T, TL), (T', TL'), ENV) = 
        if T' :: Variable then 
            if BV? == undefined then
                matchArgs*(TL, TL', (ENV, (T' |-> T)))
            else
                if BV? == T then
                    matchArgs*(TL, TL', ENV)
                else
                    errEnv
                fi
            fi
        else
            if T' == T then
                matchArgs*(TL, TL', ENV)
            else
                errEnv
            fi
        fi 
    if BV? := ENV[T'] .
    eq matchArgs*(TL, TL', ENV) = errEnv [owise] .
endfm

fmod GOAL-HANDLING is
    pr LITERAL-MATCHING .
    pr ENV-APPLYING .
    pr ILP-OUTPUT .
    pr GOAL-LIST .
    pr RENAME-VARS .

    vars POS NEG BK BK' : TermSet .
    vars MRS MRS' : BoundRuleSet .
    vars BRS BRS' : BoundRuleSet .
    vars MLL : BoundLiteralList .
    vars BLL : BoundLiteralList .
    vars BL BL' : BoundLiteral .
    vars BRS? : [BoundRuleSet] .
    vars ML : MetaLiteral .
    vars SOVar : Variable .
    vars ENV? ExtractedEnv : Env&Err .
    vars BR ParentBR SubBR : BoundRule .
    vars MR RenamedMR ParentMR SubMR : MetaRule .
    vars G Fact : Term .
    vars GL : GoalList .
    vars PATH : Path .
    vars N N' ParentDepth : Nat .
    vars ENV ParentEnv SubEnv : Env .
    vars STACK : ContextStack .

    ----------------------------------------------------------
    --- Checking coverage
    ----------------------------------------------------------
    op isCovered : Term BoundRuleSet TermSet Nat -> Bool .
    eq isCovered(G, BRS, BK, N) = if (G in BK) then true else isCoveredByRules(G, BRS, BK, N) fi .
    
    op isCoveredByRules : Term BoundRuleSet TermSet Nat -> Bool .
    ceq isCoveredByRules(G, BRS, BK, N) = BRS' =/= empty 
    if BRS' := checkGoals({goal: G, rules: BRS, path: nil, depth: 0, stack: emptyStack}, BK, BRS, N) .
    
    op coverAnyNEG : BoundRuleSet TermSet TermSet Nat -> Bool .
    eq coverAnyNEG(BRS, emptyTS, BK, N) = false .
    eq coverAnyNEG(BRS, G | NEG, BK, N) = if isCovered(G, BRS, BK, N) then true else coverAnyNEG(BRS, NEG, BK, N) fi .
    
    ----------------------------------------------------------
    --- Handling goals to find a clause set
    ----------------------------------------------------------
    op proceedGoals : GoalList TermSet MetaRuleSet Bound TermSet -> BoundRuleSet .
    eq proceedGoals(nil, BK, MRS', N, NEG) = empty .
    eq proceedGoals({goal: G, rules: empty, path: PATH, depth: N', stack: STACK} GL, BK, MRS', N, NEG) = proceedGoals(GL, BK, MRS', N, NEG) .
    
    ceq proceedGoals({goal: G, rules: (MR, MRS), path: PATH, depth: N', stack: STACK} GL, BK, MRS', N, NEG) = 
        if ENV? == errEnv then 
            proceedGoals({goal: G, rules: MRS, path: PATH, depth: N', stack: STACK} GL, BK, MRS', N, NEG)
        else 
            proceedGoals(
                {lits: getBody(RenamedMR), facts: BK, path: [RenamedMR, ENV?] PATH, depth: N', stack: STACK} 
                {goal: G, rules: MRS, path: PATH, depth: N', stack: STACK} 
                GL, BK, MRS', N, NEG
            )
        fi
    if RenamedMR := renameVarsMR(MR, N')
    /\ ENV? := matchLiteral(G, getHead(RenamedMR)) .
    
    ceq proceedGoals({lits: nil, facts: BK', path: PATH, depth: N', stack: emptyStack} GL, BK, MRS', N, NEG) =
        if coverAnyNEG(BRS, NEG, BK, N) then 
            proceedGoals(GL, BK, MRS', N, NEG)
        else 
            BRS 
        fi
    if BRS := buildClauseSet(PATH) .

    ceq proceedGoals({lits: nil, facts: BK', path: [SubMR, SubEnv] PATH, depth: N', stack: mctx(BL, MLL, ParentMR, ParentEnv, ParentDepth) | STACK} GL, BK, MRS', N, NEG) =
        if ExtractedEnv == errEnv then
            proceedGoals(GL, BK, MRS', N, NEG)
        else
            proceedGoals(
                {
                    lits: MLL, 
                    facts: BK, 
                    path: [ParentMR, (ParentEnv, ExtractedEnv)] [SubMR, SubEnv] PATH, 
                    depth: ParentDepth, 
                    stack: STACK
                }
                GL, BK, MRS', N, NEG
            )
        fi
    if ExtractedEnv := matchArgs(getArgs(toTerm(BL << SubEnv)), getFOVars(BL)) .

    ceq proceedGoals({lits: ML MLL, facts: BK', path: [MR, ENV] PATH, depth: N', stack: STACK} GL, BK, MRS', N, NEG) = 
        if isGroundLiteral(BL) then
            if (hasElt(BL, BK)) then
                proceedGoals({lits: MLL, facts: BK, path: [MR, ENV] PATH, depth: N', stack: STACK} GL, BK, MRS', N, NEG)
            else
                if (N' < N) and isRecursiveCall(MR, ENV, BL) then
                    if (MLL == nil) then
                        --- 
                        proceedGoals(
                            {goal: toTerm(BL), rules: MRS', path: [MR, ENV] PATH, depth: (N' + 1), stack: STACK} GL, 
                            BK, MRS', N, NEG
                        )
                    else
                        proceedGoals(
                            {goal: toTerm(BL), rules: MRS', path: PATH, depth: (N' + 1), stack: mctx(BL, MLL, MR, ENV, N') | STACK} GL,
                            BK, MRS', N, NEG
                        )
                    fi
                else
                    proceedGoals(GL, BK, MRS', N, NEG)
                fi
            fi
        else
            proceedGoalsWithFacts({lits: ML MLL, facts: BK', path: [MR, ENV] PATH, depth: N', stack: STACK} GL, BK, MRS', N, NEG)
        fi
    if BL := (ML << ENV) .

    op isRecursiveCall : MetaRule Env BoundLiteral -> Bool .
    ceq isRecursiveCall(MR, ENV, BL) = getSOVar(BL) == getSOVar(BL') and (BL =/= BL')
    if BL' := (getHead(MR) << ENV) .
    
    op proceedGoalsWithFacts : GoalList TermSet MetaRuleSet Bound TermSet -> BoundRuleSet .
    
    ceq proceedGoalsWithFacts({lits: ML MLL, facts: emptyTS, path: [MR, ENV] PATH, depth: N', stack: STACK} GL, BK, MRS', N, NEG) = 
        if (N' < N) and (size(getBody(MR)) > 1) then
            if (MLL == nil) and hasSOVarOnly(BL) then
                --- Optimize
                proceedGoals(
                    {
                        goal: toTerm(BL << (getSOVar(BL) |-> getPredInvName(N'))), 
                        rules: MRS', 
                        path: [MR, (ENV, getSOVar(BL) |-> getPredInvName(N'))] PATH, 
                        depth: (N' + 1),
                        stack: STACK
                    }
                    GL
                    , 
                    BK, MRS', N, NEG
                )
            else
                proceedGoals(
                    GL
                    {
                        goal: toTerm(BL << (getSOVar(BL) |-> getPredInvName(N'))), 
                        rules: MRS', 
                        path: PATH, 
                        depth: (N' + 1),
                        stack: mctx(BL, MLL, MR, (ENV, getSOVar(BL) |-> getPredInvName(N')), N') | STACK
                    }, 
                    BK, MRS', N, NEG
                )
            fi
        else
            proceedGoals(GL, BK, MRS', N, NEG)
        fi 
    if BL := (ML << ENV) .

    ceq proceedGoalsWithFacts({lits: ML MLL, facts: Fact | BK', path: [MR, ENV] PATH, depth: N', stack: STACK} GL, BK, MRS', N, NEG) = 
        if ENV? == errEnv then
            proceedGoalsWithFacts({lits: ML MLL, facts: BK', path: [MR, ENV] PATH, depth: N', stack: STACK} GL, BK, MRS', N, NEG)
        else
            proceedGoals(
                {lits: MLL, facts: BK, path: [MR, (ENV, ENV?)] PATH, depth: N', stack: STACK}
                {lits: ML MLL, facts: BK', path: [MR, ENV] PATH, depth: N', stack: STACK} GL, 
                BK, MRS', N, NEG
            )
        fi
    if BL := (ML << ENV)
    /\ ENV? := matchLiteral(Fact, BL) .

    ----------------------------------------------------------
    --- Handling goals to check coverage
    ----------------------------------------------------------
    op checkGoals : GoalList TermSet BoundRuleSet Bound -> BoundRuleSet .
    eq checkGoals(nil, BK, BRS', N) = empty .
    eq checkGoals({goal: G, rules: empty, path: PATH, depth: N', stack: STACK} GL, BK, BRS', N) = checkGoals(GL, BK, BRS', N) .
    
    ceq checkGoals({goal: G, rules: (BR, BRS), path: PATH, depth: N', stack: STACK} GL, BK, BRS', N) = 
        if ENV? == errEnv then 
            checkGoals({goal: G, rules: BRS, path: PATH, depth: N', stack: STACK} GL, BK, BRS', N) 
        else 
            checkGoals(
                {lits: getBody(BR), facts: BK, path: [BR, ENV?] PATH, depth: N', stack: STACK} 
                {goal: G, rules: BRS, path: PATH, depth: N', stack: STACK} 
                GL, BK, BRS', N
            )
        fi
    if ENV? := matchLiteral(G, getHead(BR)) .

    eq checkGoals({lits: nil, facts: BK', path: PATH, depth: N', stack: emptyStack} GL, BK, BRS', N) = buildClauseSet2(PATH) .

    ceq checkGoals({lits: nil, facts: BK', path: [SubBR, SubEnv] PATH, depth: N', stack: bctx(BL, BLL, ParentBR, ParentEnv, ParentDepth) | STACK} GL, BK, BRS', N) =
        if ExtractedEnv == errEnv then
            checkGoals(GL, BK, BRS', N)
        else
            checkGoals(
                {
                    lits: BLL, 
                    facts: BK, 
                    path: [ParentBR, (ParentEnv, ExtractedEnv)] [SubBR, SubEnv] PATH, 
                    depth: ParentDepth, 
                    stack: STACK
                }
                GL, BK, BRS', N
            )
        fi
    if ExtractedEnv := matchArgs(getArgs(toTerm(BL << SubEnv)), getFOVars(BL)) .

    ceq checkGoals({lits: BL BLL, facts: BK', path: [BR, ENV] PATH, depth: N', stack: STACK} GL, BK, BRS', N) = 
        if isGroundLiteral(BL') then
            if (hasElt(BL', BK)) then
                checkGoals({lits: BLL, facts: BK', path: [BR, ENV] PATH, depth: N', stack: STACK} GL, BK, BRS', N)
            else
                if (N' < N) and hasRuleByQid(getSOVar(BL'), BRS') then
                    if (BLL == nil) then
                        checkGoals(
                            GL {goal: toTerm(BL'), rules: BRS', path: [BR, ENV] PATH, depth: (N' + 1), stack: STACK}, 
                            BK, BRS', N
                        )
                    else
                        checkGoals(
                            GL {goal: toTerm(BL'), rules: BRS', path: PATH, depth: (N' + 1), stack: bctx(BL', BLL, BR, ENV, N') | STACK}, 
                            BK, BRS', N
                        )
                    fi
                else
                    checkGoals(GL, BK, BRS', N)
                fi 
            fi
        else
            checkGoalsWithFacts({lits: BL BLL, facts: BK', path: [BR, ENV] PATH, depth: N', stack: STACK} GL, BK, BRS', N)
        fi
    if BL' := (BL << ENV) .
    
    op checkGoalsWithFacts : GoalList TermSet BoundRuleSet Bound -> BoundRuleSet .
    
    ceq checkGoalsWithFacts({lits: BL BLL, facts: emptyTS, path: [BR, ENV] PATH, depth: N', stack: STACK} GL, BK, BRS', N) = 
        if (N' < N) and hasRuleByQid(getSOVar(BL'), BRS') then
            if (BLL == nil) then
                checkGoals(
                    GL {goal: toTerm(BL'), rules: BRS', path: [BR, ENV] PATH, depth: (N' + 1), stack: STACK}, 
                    BK, BRS', N
                )
            else
                checkGoals(
                    GL {
                        goal: toTerm(BL'), 
                        rules: BRS', 
                        path: PATH, 
                        depth: (N' + 1), 
                        stack: bctx(BL', BLL, BR, ENV, N') | STACK
                    }, 
                    BK, BRS', N
                )
            fi
        else
            checkGoals(GL, BK, BRS', N)
        fi
    if BL' := (BL << ENV) .

    ceq checkGoalsWithFacts({lits: BL BLL, facts: Fact | BK', path: [BR, ENV] PATH, depth: N', stack: STACK} GL, BK, BRS', N) = 
        if ENV? == errEnv then
            checkGoalsWithFacts({lits: BL BLL, facts: BK', path: [BR, ENV] PATH, depth: N', stack: STACK} GL, BK, BRS', N)
        else
            checkGoals(
                {lits: BLL, facts: BK, path: [BR, (ENV, ENV?)] PATH, depth: N', stack: STACK}
                {lits: BL BLL, facts: BK', path: [BR, ENV] PATH, depth: N', stack: STACK} GL, 
                BK, BRS', N
            )
        fi
    if BL' := (BL << ENV)
    /\ ENV? := matchLiteral(Fact, BL') .
endfm

fmod MAUDE-ILP is
    pr ILP-PARSING-INPUT .
    pr GOAL-HANDLING .
    pr ILP-OUTPUT .
    vars MRS MRS' : MetaRuleSet .
    vars POS NEG BK : TermSet .
    vars BRS BRS' : BoundRuleSet .
    vars G : Term .
    vars N : Nat .
    
    op learn`(`) : -> BoundRuleSet .
    eq learn() = learn(0) .

    op learn : Bound -> BoundRuleSet .
    eq learn(N) = learn(getPOS(), getNEG(), getMetaRules(), getBK(), N, empty) .
    
    op learn : TermSet TermSet MetaRuleSet TermSet Bound BoundRuleSet -> BoundRuleSet .
    eq learn(emptyTS, NEG, MRS, BK, N, BRS') = BRS' .
    
    eq learn(G | POS, NEG, MRS, BK, N, BRS') = 
        if isCovered(G, BRS', BK, N) then
            learn(POS, NEG, MRS, BK, N, BRS')
        else
            learn*(G | POS, NEG, MRS, BK, N, BRS')
        fi .
        
    op learn* : TermSet TermSet MetaRuleSet TermSet Bound BoundRuleSet -> BoundRuleSet .
    
    ceq learn*(G | POS, NEG, MRS, BK, N, BRS') =
        if BRS == empty then
            empty
        else
            learn(POS, NEG, MRS, BK, N, (BRS, BRS'))
        fi
    if BRS := proceedGoals({goal: G, rules: MRS, path: nil, depth: 0, stack: emptyStack}, BK, MRS, N, NEG) .
endfm