load ILP-SEARCH.maude
load head-tail-case.maude

fmod TEST-SEARCH-HEAD-TAIL is
  protecting ILP-SEARCH .
  protecting HEAD-TAIL-CASE .
  protecting META-LEVEL .

  op M-PROB : -> [Module] .
  eq M-PROB = upModule('HEAD-TAIL-CASE, false) .
  
  op POS-Data : -> TermList . eq POS-Data = flattenList(getEqRhs(M-PROB, 'POS)) .
  op NEG-Data : -> TermList . eq NEG-Data = flattenList(getEqRhs(M-PROB, 'NEG)) .
  op BK-Data : -> TermList . eq BK-Data = flattenList(getEqRhs(M-PROB, 'BK)) .

  --- Chạy thuật toán Metagol (Set Cover)
  op Induced-Program : -> MetasubList .
  eq Induced-Program = learn(POS-Data, NEG-Data, BK-Data, emptySub) .

endfm

set trace off .

--- KỲ VỌNG: emptySub (Vì máy sẽ "bí đường", không thể lột mảng 2 lần chỉ với 1 luật chain)
reduce in TEST-SEARCH-HEAD-TAIL : Induced-Program .