load ILP-SEARCH.maude
load grandparent-ilp-new2.maude

fmod TEST-SEARCH is
  protecting ILP-SEARCH .
  protecting GRANDPARENT-ILP-NEW2 .
  protecting META-LEVEL .

  op M-PROB : -> [Module] .
  eq M-PROB = upModule('GRANDPARENT-ILP-NEW2, false) .
  
  op POS-Data : -> TermList .
  eq POS-Data = flattenList(getEqRhs(M-PROB, 'POS)) .
  
  op NEG-Data : -> TermList . 
  eq NEG-Data = flattenList(getEqRhs(M-PROB, 'NEG)) .
  
  op BK-Data : -> TermList . 
  eq BK-Data = flattenList(getEqRhs(M-PROB, 'BK)) .
  
  op MR-Data : -> TermList . 
  eq MR-Data = extractMetarules(getEqRhs(M-PROB, 'METARULES)) .

  op Induced-Program : -> ILPClauseSet .
  eq Induced-Program = learn(POS-Data, NEG-Data, BK-Data, emptyClauseSet, MR-Data) .

endfm

set trace off .
reduce in TEST-SEARCH : Induced-Program .