load ILP-SEARCH.maude
load droplast-case.maude

fmod TEST-DROP-LAST is
  protecting ILP-SEARCH .
  protecting MAP-DROPLAST-CASE .
  protecting META-LEVEL .

  eq MAX-DEPTH = 5 .
  
  op M-PROB : -> [Module] .
  eq M-PROB = upModule('MAP-DROPLAST-CASE, false) .
  
  op POS-Data : -> TermList . 
  eq POS-Data = flattenList(getEqRhs(M-PROB, 'POS)) .
  
  op NEG-Data : -> TermList . 
  eq NEG-Data = flattenList(getEqRhs(M-PROB, 'NEG)) .
  
  op BK-Data : -> TermSet . 
  eq BK-Data = listToSet(flattenList(getEqRhs(M-PROB, 'BK))) .

  op MR-Data : -> TermList . 
  eq MR-Data  = flattenList(getEqRhs(M-PROB, 'METARULES)) .

  op Induced-Program : -> ILPClauseSet .
  eq Induced-Program = learn(POS-Data, NEG-Data, BK-Data, emptyClauseSet, MR-Data) .
endfm

--- Lệnh thực thi để thấy kết quả Object-level sạch sẽ
set show timing on .
reduce in TEST-DROP-LAST : simulate(Induced-Program) .