load ILP-SEARCH.maude
load droplast-case.maude

fmod TEST-DROP-LAST is
  protecting ILP-SEARCH .
  protecting MAP-DROPLAST-CASE .
  protecting META-LEVEL .

  --- Cấu hình độ sâu
  eq MAX-DEPTH-VAL = 5 .

  op M-PROB : -> [Module] .
  eq M-PROB = upModule('MAP-DROPLAST-CASE, false) .
  
  op POS-Data : -> TermList . eq POS-Data = flattenList(getEqRhs(M-PROB, 'POS)) .
  op NEG-Data : -> TermList . eq NEG-Data = flattenList(getEqRhs(M-PROB, 'NEG)) .
  op BK-Data : -> TermSet . eq BK-Data = listToSet(flattenList(getEqRhs(M-PROB, 'BK))) .
  op MR-Data : -> TermList . eq MR-Data  = flattenList(getEqRhs(M-PROB, 'METARULES)) .

  op Induced-Program : -> ILPClauseSet .
  eq Induced-Program = learn(POS-Data, NEG-Data, BK-Data, emptyClauseSet, MR-Data) .

  --- HIỂN THỊ DẠNG STRING ĐẸP
  op Pretty-Program : -> String .
  eq Pretty-Program = simulateEqs(getInducedEquations(Induced-Program)) .
endfm

set show timing on .
reduce in TEST-DROP-LAST : Pretty-Program .