load ILP-SEARCH.maude
load graph-colouring.maude

fmod TEST-SEARCH-GRAPH-COLOURING is
  protecting ILP-DISPLAY .
  protecting GRAPH-COLOURING-CASE .
  protecting META-LEVEL .

  --- Thiết lập độ sâu tìm kiếm
  eq MAX-DEPTH = 5 .

  --- Lấy bối cảnh module GRAPH-COLOURING-CASE để trích xuất dữ liệu
  op M-PROB : -> [Module] .
  eq M-PROB = upModule('GRAPH-COLOURING-CASE, false) .
  
  --- Trích xuất danh sách Positive Examples (target(e))
  op POS-Data : -> TermList .
  eq POS-Data = flattenList(getEqRhs(M-PROB, 'POS)) .
  
  --- Trích xuất danh sách Negative Examples (target(a), target(b), ...)
  op NEG-Data : -> TermList . 
  eq NEG-Data = flattenList(getEqRhs(M-PROB, 'NEG)) .
  
  --- Chuyển đổi Background Knowledge sang dạng Set để tra cứu O(1)
  op BK-Data : -> TermSet . 
  eq BK-Data = listToSet(flattenList(getEqRhs(M-PROB, 'BK))) .
  
  --- Trích xuất các khuôn mẫu Metarules
  op MR-Data : -> TermList .
  eq MR-Data  = flattenList(getEqRhs(M-PROB, 'METARULES)) .

  --- Khởi động thuật toán ILP để tìm bộ luật
  op Induced-Program : -> ILPClauseSet .
  eq Induced-Program = learn(POS-Data, NEG-Data, BK-Data, MR-Data) .
endfm

--- BẬT ĐO THỜI GIAN VÀ CHẠY THỬ NGHIỆM
set show timing on .
reduce in TEST-SEARCH-GRAPH-COLOURING : simulate(Induced-Program) .