load ../MaudeILP.maude .

fmod ILP-PROBLEM is 
    pr ILP-DEFINITION-INPUT .
    
    sort Person .
    subsort Person < Param .

    --- KHAI BÁO 3 NHÂN VẬT (Chú ý thứ tự Alphabet: ann < bob < cal)
    ops ann bob cal : -> Person [ctor] .

    op parent : Person Person -> Pred [ctor] .
    op sibling : Person Person -> Pred [ctor comm] .
    op aunt : Person Person -> Pred [ctor] .

    eq BK =
        parent(ann, bob)
        sibling(bob, cal) . 
        --- Maude tự lưu sibling(bob, cal) vì 'bob' đứng trước 'cal'

    eq POS =
        aunt(ann, cal) .


    vars P Q R : Pred .
    vars A B C : Person .

    --- METARULE ĐẢO BIẾN (Chú ý R(B,C) chứ không phải R(C,B))
    eq METARULES =
        (P(A,B) :- (Q(A,C)) (R(B,C)))
        [nonexec] .
endfm

select MAUDE-ILP .
red learn() .