load ../MaudeILP.maude .

fmod ILP-PROBLEM is
    pr ILP-DEFINITION-INPUT .

    sort Person .
    subsort Person < Param .

    ops ann bob cal dawn : -> Person [ctor] .
    ops parent grandparent great-grandparent : Person Person -> Pred [ctor] .

    eq BK =
        parent(ann, bob)
        parent(bob, cal)
        parent(cal, dawn) .


    eq POS = great-grandparent(ann, dawn) .

    eq NEG = great-grandparent(ann, cal) .

    vars P Q R : Pred .
    vars A B C : Person .

    eq METARULES =
        (P(A,B) :- (Q(A,C)) (R(C,B)))
        [nonexec] .
endfm

select MAUDE-ILP .
red learn() .
red learn(1) .
